import u9g_webp from "./images/teams/u9g.webp";
import u9g_png from "./images/teams/u9g.png";
import u9g_jpg from "./images/teams/u9g.jpg";
import u9f_webp from "./images/teams/u9f.webp";
import u9f_png from "./images/teams/u9f.png";
import u9f_jpg from "./images/teams/u9f.jpg";
import u7_2_2_webp from "./images/teams/u7-2-2.webp";
import u7_2_2_png from "./images/teams/u7-2-2.png";
import u7_2_2_jpg from "./images/teams/u7-2-2.jpg";
import u18g1_webp from "./images/teams/u18g1.webp";
import u18g1_png from "./images/teams/u18g1.png";
import u18g1_jpg from "./images/teams/u18g1.jpg";
import u15f1et2_webp from "./images/teams/u15f1et2.webp";
import u15f1et2_png from "./images/teams/u15f1et2.png";
import u15f1et2_jpg from "./images/teams/u15f1et2.jpg";
import u13m2_webp from "./images/teams/u13m2.webp";
import u13m2_png from "./images/teams/u13m2.png";
import u13m2_jpg from "./images/teams/u13m2.jpg";
import u13f_webp from "./images/teams/u13f.webp";
import u13f_png from "./images/teams/u13f.png";
import u13f_jpg from "./images/teams/u13f.jpg";
import u13_webp from "./images/teams/u13.webp";
import u13_png from "./images/teams/u13.png";
import u13_jpg from "./images/teams/u13.jpg";
import u11g_webp from "./images/teams/u11g.webp";
import u11g_png from "./images/teams/u11g.png";
import u11g_jpg from "./images/teams/u11g.jpg";
import u11F_webp from "./images/teams/u11F.webp";
import u11F_png from "./images/teams/u11F.png";
import u11F_jpg from "./images/teams/u11F.jpg";
import r2f_webp from "./images/teams/r2f.webp";
import r2f_png from "./images/teams/r2f.png";
import r2f_jpg from "./images/teams/r2f.jpg";
import pnm_webp from "./images/teams/pnm.webp";
import pnm_png from "./images/teams/pnm.png";
import pnm_jpg from "./images/teams/pnm.jpg";
import d2_webp from "./images/teams/d2.webp";
import d2_png from "./images/teams/d2.png";
import d2_jpg from "./images/teams/d2.jpg";
import R3_webp from "./images/teams/R3.webp";
import R3_png from "./images/teams/R3.png";
import R3_jpg from "./images/teams/R3.jpg";
import Pnfsponsor_webp from "./images/teams/Pnfsponsor.webp";
import Pnfsponsor_png from "./images/teams/Pnfsponsor.png";
import Pnfsponsor_jpg from "./images/teams/Pnfsponsor.jpg";
import Pnf_webp from "./images/teams/Pnf.webp";
import Pnf_png from "./images/teams/Pnf.png";
import Pnf_jpg from "./images/teams/Pnf.jpg";
import news20251105_webp from "./images/news/news20251105.webp";
import news20251105_png from "./images/news/news20251105.png";
import news20251105_jpg from "./images/news/news20251105.jpg";
import news20251102_webp from "./images/news/news20251102.webp";
import news20251102_png from "./images/news/news20251102.png";
import news20251102_jpg from "./images/news/news20251102.jpg";
import news20251017_webp from "./images/news/news20251017.webp";
import news20251017_png from "./images/news/news20251017.png";
import news20251017_jpg from "./images/news/news20251017.jpg";
import news20250923_webp from "./images/news/news20250923.webp";
import news20250923_png from "./images/news/news20250923.png";
import news20250923_jpg from "./images/news/news20250923.jpg";
import terrain_webp from "./images/misc/terrain.webp";
import terrain_png from "./images/misc/terrain.png";
import terrain_jpg from "./images/misc/terrain.jpg";
import planning20252026_webp from "./images/misc/planning20252026.webp";
import planning20252026_png from "./images/misc/planning20252026.png";
import planning20252026_jpg from "./images/misc/planning20252026.jpg";
import zecarrosserie_webp from "./images/logo/zecarrosserie.webp";
import zecarrosserie_png from "./images/logo/zecarrosserie.png";
import zecarrosserie_jpg from "./images/logo/zecarrosserie.jpg";
import united_avocats_webp from "./images/logo/united avocats.webp";
import united_avocats_png from "./images/logo/united avocats.png";
import united_avocats_jpg from "./images/logo/united avocats.jpg";
import service_civique_webp from "./images/logo/service civique.webp";
import service_civique_png from "./images/logo/service civique.png";
import service_civique_jpg from "./images/logo/service civique.jpg";
import pompes_funebres_webp from "./images/logo/pompes funebres.webp";
import pompes_funebres_png from "./images/logo/pompes funebres.png";
import pompes_funebres_jpg from "./images/logo/pompes funebres.jpg";
import minute_blonde_webp from "./images/logo/minute blonde.webp";
import minute_blonde_png from "./images/logo/minute blonde.png";
import minute_blonde_jpg from "./images/logo/minute blonde.jpg";
import market_webp from "./images/logo/market.webp";
import market_png from "./images/logo/market.png";
import market_jpg from "./images/logo/market.jpg";
import logo_fiducial_webp from "./images/logo/logo_fiducial.webp";
import logo_fiducial_png from "./images/logo/logo_fiducial.png";
import logo_fiducial_jpg from "./images/logo/logo_fiducial.jpg";
import logo_letablier_600_webp from "./images/logo/logo-letablier-600.webp";
import logo_letablier_600_png from "./images/logo/logo-letablier-600.png";
import logo_letablier_600_jpg from "./images/logo/logo-letablier-600.jpg";
import locevasion_webp from "./images/logo/locevasion.webp";
import locevasion_png from "./images/logo/locevasion.png";
import locevasion_jpg from "./images/logo/locevasion.jpg";
import lebeau_martina_webp from "./images/logo/lebeau-martina.webp";
import lebeau_martina_png from "./images/logo/lebeau-martina.png";
import lebeau_martina_jpg from "./images/logo/lebeau-martina.jpg";
import lcbo_logo_webp from "./images/logo/lcbo_logo.webp";
import lcbo_logo_png from "./images/logo/lcbo_logo.png";
import lcbo_logo_jpg from "./images/logo/lcbo_logo.jpg";
import lasergame_webp from "./images/logo/lasergame.webp";
import lasergame_png from "./images/logo/lasergame.png";
import lasergame_jpg from "./images/logo/lasergame.jpg";
import kokomo_webp from "./images/logo/kokomo.webp";
import kokomo_png from "./images/logo/kokomo.png";
import kokomo_jpg from "./images/logo/kokomo.jpg";
import immoservices_webp from "./images/logo/immoservices.webp";
import immoservices_png from "./images/logo/immoservices.png";
import immoservices_jpg from "./images/logo/immoservices.jpg";
import hortense_webp from "./images/logo/hortense.webp";
import hortense_png from "./images/logo/hortense.png";
import hortense_jpg from "./images/logo/hortense.jpg";
import home_me_webp from "./images/logo/home me.webp";
import home_me_png from "./images/logo/home me.png";
import home_me_jpg from "./images/logo/home me.jpg";
import hG_webp from "./images/logo/hG.webp";
import hG_png from "./images/logo/hG.png";
import hG_jpg from "./images/logo/hG.jpg";
import freres_chaussettes_webp from "./images/logo/freres chaussettes.webp";
import freres_chaussettes_png from "./images/logo/freres chaussettes.png";
import freres_chaussettes_jpg from "./images/logo/freres chaussettes.jpg";
import fossey_webp from "./images/logo/fossey.webp";
import fossey_png from "./images/logo/fossey.png";
import fossey_jpg from "./images/logo/fossey.jpg";
import emzel_webp from "./images/logo/emzel.webp";
import emzel_png from "./images/logo/emzel.png";
import emzel_jpg from "./images/logo/emzel.jpg";
import desbont_webp from "./images/logo/desbont.webp";
import desbont_png from "./images/logo/desbont.png";
import desbont_jpg from "./images/logo/desbont.jpg";
import cre_habitat_webp from "./images/logo/cre habitat.webp";
import cre_habitat_png from "./images/logo/cre habitat.png";
import cre_habitat_jpg from "./images/logo/cre habitat.jpg";
import cphoto_webp from "./images/logo/cphoto.webp";
import cphoto_png from "./images/logo/cphoto.png";
import cphoto_jpg from "./images/logo/cphoto.jpg";
import arttif_webp from "./images/logo/arttif.webp";
import arttif_png from "./images/logo/arttif.png";
import arttif_jpg from "./images/logo/arttif.jpg";
import a_tri_home_webp from "./images/logo/a tri home.webp";
import a_tri_home_png from "./images/logo/a tri home.png";
import a_tri_home_jpg from "./images/logo/a tri home.jpg";
import REALISM_logo_quadri_bleu_orange_webp from "./images/logo/REALISM_logo_quadri_bleu_orange.webp";
import REALISM_logo_quadri_bleu_orange_png from "./images/logo/REALISM_logo_quadri_bleu_orange.png";
import REALISM_logo_quadri_bleu_orange_jpg from "./images/logo/REALISM_logo_quadri_bleu_orange.jpg";
import LOGO_FFBB_webp from "./images/logo/LOGO-FFBB.webp";
import LOGO_FFBB_png from "./images/logo/LOGO-FFBB.png";
import LOGO_FFBB_jpg from "./images/logo/LOGO-FFBB.jpg";
import Foissier_CMJN_contour_webp from "./images/logo/Foissier_CMJN_contour.webp";
import Foissier_CMJN_contour_png from "./images/logo/Foissier_CMJN_contour.png";
import Foissier_CMJN_contour_jpg from "./images/logo/Foissier_CMJN_contour.jpg";
import LCBO_Basket_histoire_webp from "./images/history/LCBO_Basket_histoire.webp";
import LCBO_Basket_histoire_png from "./images/history/LCBO_Basket_histoire.png";
import LCBO_Basket_histoire_jpg from "./images/history/LCBO_Basket_histoire.jpg";
import LCBO_Basket_1972_sous_la_neige_webp from "./images/history/LCBO-Basket-1972-sous-la-neige.webp";
import LCBO_Basket_1972_sous_la_neige_png from "./images/history/LCBO-Basket-1972-sous-la-neige.png";
import LCBO_Basket_1972_sous_la_neige_jpg from "./images/history/LCBO-Basket-1972-sous-la-neige.jpg";
import LCBO_Basket_1972_match_dans_la_neige_webp from "./images/history/LCBO-Basket-1972-match-dans-la-neige.webp";
import LCBO_Basket_1972_match_dans_la_neige_png from "./images/history/LCBO-Basket-1972-match-dans-la-neige.png";
import LCBO_Basket_1972_match_dans_la_neige_jpg from "./images/history/LCBO-Basket-1972-match-dans-la-neige.jpg";

export { u9g_webp, u9g_png, u9g_jpg, u9f_webp, u9f_png, u9f_jpg, u7_2_2_webp, u7_2_2_png, u7_2_2_jpg, u18g1_webp, u18g1_png, u18g1_jpg, u15f1et2_webp, u15f1et2_png, u15f1et2_jpg, u13m2_webp, u13m2_png, u13m2_jpg, u13f_webp, u13f_png, u13f_jpg, u13_webp, u13_png, u13_jpg, u11g_webp, u11g_png, u11g_jpg, u11F_webp, u11F_png, u11F_jpg, r2f_webp, r2f_png, r2f_jpg, pnm_webp, pnm_png, pnm_jpg, d2_webp, d2_png, d2_jpg, R3_webp, R3_png, R3_jpg, Pnfsponsor_webp, Pnfsponsor_png, Pnfsponsor_jpg, Pnf_webp, Pnf_png, Pnf_jpg, news20251105_webp, news20251105_png, news20251105_jpg, news20251102_webp, news20251102_png, news20251102_jpg, news20251017_webp, news20251017_png, news20251017_jpg, news20250923_webp, news20250923_png, news20250923_jpg, terrain_webp, terrain_png, terrain_jpg, planning20252026_webp, planning20252026_png, planning20252026_jpg, zecarrosserie_webp, zecarrosserie_png, zecarrosserie_jpg, united_avocats_webp, united_avocats_png, united_avocats_jpg, service_civique_webp, service_civique_png, service_civique_jpg, pompes_funebres_webp, pompes_funebres_png, pompes_funebres_jpg, minute_blonde_webp, minute_blonde_png, minute_blonde_jpg, market_webp, market_png, market_jpg, logo_fiducial_webp, logo_fiducial_png, logo_fiducial_jpg, logo_letablier_600_webp, logo_letablier_600_png, logo_letablier_600_jpg, locevasion_webp, locevasion_png, locevasion_jpg, lebeau_martina_webp, lebeau_martina_png, lebeau_martina_jpg, lcbo_logo_webp, lcbo_logo_png, lcbo_logo_jpg, lasergame_webp, lasergame_png, lasergame_jpg, kokomo_webp, kokomo_png, kokomo_jpg, immoservices_webp, immoservices_png, immoservices_jpg, hortense_webp, hortense_png, hortense_jpg, home_me_webp, home_me_png, home_me_jpg, hG_webp, hG_png, hG_jpg, freres_chaussettes_webp, freres_chaussettes_png, freres_chaussettes_jpg, fossey_webp, fossey_png, fossey_jpg, emzel_webp, emzel_png, emzel_jpg, desbont_webp, desbont_png, desbont_jpg, cre_habitat_webp, cre_habitat_png, cre_habitat_jpg, cphoto_webp, cphoto_png, cphoto_jpg, arttif_webp, arttif_png, arttif_jpg, a_tri_home_webp, a_tri_home_png, a_tri_home_jpg, REALISM_logo_quadri_bleu_orange_webp, REALISM_logo_quadri_bleu_orange_png, REALISM_logo_quadri_bleu_orange_jpg, LOGO_FFBB_webp, LOGO_FFBB_png, LOGO_FFBB_jpg, Foissier_CMJN_contour_webp, Foissier_CMJN_contour_png, Foissier_CMJN_contour_jpg, LCBO_Basket_histoire_webp, LCBO_Basket_histoire_png, LCBO_Basket_histoire_jpg, LCBO_Basket_1972_sous_la_neige_webp, LCBO_Basket_1972_sous_la_neige_png, LCBO_Basket_1972_sous_la_neige_jpg, LCBO_Basket_1972_match_dans_la_neige_webp, LCBO_Basket_1972_match_dans_la_neige_png, LCBO_Basket_1972_match_dans_la_neige_jpg };